[2024-03-29T17:27:47.989+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_Teste.captura_conta_dados manual__2024-03-29T17:27:45.786392+00:00 [queued]>
[2024-03-29T17:27:47.995+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_Teste.captura_conta_dados manual__2024-03-29T17:27:45.786392+00:00 [queued]>
[2024-03-29T17:27:47.996+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-29T17:27:48.030+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): captura_conta_dados> on 2024-03-29 17:27:45.786392+00:00
[2024-03-29T17:27:48.034+0000] {standard_task_runner.py:60} INFO - Started process 94 to run task
[2024-03-29T17:27:48.035+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_Teste', 'captura_conta_dados', 'manual__2024-03-29T17:27:45.786392+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_test.py', '--cfg-path', '/tmp/tmpe2mhv148']
[2024-03-29T17:27:48.037+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask captura_conta_dados
[2024-03-29T17:27:48.072+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_Teste.captura_conta_dados manual__2024-03-29T17:27:45.786392+00:00 [running]> on host dedf4740d4fb
[2024-03-29T17:27:48.516+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_Teste' AIRFLOW_CTX_TASK_ID='captura_conta_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T17:27:45.786392+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T17:27:45.786392+00:00'
[2024-03-29T17:27:50.612+0000] {python.py:202} INFO - Done. Returned value was: 1000
[2024-03-29T17:27:50.632+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag_Teste, task_id=captura_conta_dados, execution_date=20240329T172745, start_date=20240329T172747, end_date=20240329T172750
[2024-03-29T17:27:50.704+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T17:27:50.722+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
