[2024-03-29T20:05:30.533+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_test00.transform_data manual__2024-03-29T20:05:26.994621+00:00 [queued]>
[2024-03-29T20:05:30.541+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_test00.transform_data manual__2024-03-29T20:05:26.994621+00:00 [queued]>
[2024-03-29T20:05:30.541+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-29T20:05:30.580+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): transform_data> on 2024-03-29 20:05:26.994621+00:00
[2024-03-29T20:05:30.585+0000] {standard_task_runner.py:60} INFO - Started process 1066 to run task
[2024-03-29T20:05:30.587+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_test00', 'transform_data', 'manual__2024-03-29T20:05:26.994621+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/dag_spotify_test.py', '--cfg-path', '/tmp/tmp499flvrf']
[2024-03-29T20:05:30.589+0000] {standard_task_runner.py:88} INFO - Job 137: Subtask transform_data
[2024-03-29T20:05:30.624+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_test00.transform_data manual__2024-03-29T20:05:26.994621+00:00 [running]> on host 5eb6f8f434b5
[2024-03-29T20:05:30.745+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_test00' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T20:05:26.994621+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T20:05:26.994621+00:00'
[2024-03-29T20:05:30.746+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/src/main.py", line 22, in transform_api
    top10 = transform_json_top10(songs)
TypeError: transform_json_top10() missing 1 required positional argument: 'json_result'
[2024-03-29T20:05:30.752+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_test00, task_id=transform_data, execution_date=20240329T200526, start_date=20240329T200530, end_date=20240329T200530
[2024-03-29T20:05:30.891+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 137 for task transform_data (transform_json_top10() missing 1 required positional argument: 'json_result'; 1066)
[2024-03-29T20:05:30.920+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-29T20:05:30.932+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
